# version format
version: '{build}-{branch}'

# branches to build
branches:
  # whitelist
  only:
    - master
    - release
    - default

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# clone directory
clone_folder: c:\projects\WinToolsLib

before_build:
  - cd c:\projects\WinToolsLib

# to run your custom scripts instead of automatic MSBuild
build_script:
  - build.bat

